[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pos/login.html"
  status = 302

[[redirects]]
  from = "/pos"
  to = "/pos/login.html"
  status = 302

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/kds"
  to = "/kds/index.html"
  status = 200

[[redirects]]
  from = "/kds/"
  to = "/kds/index.html"
  status = 200

[[redirects]]
  from = "/order/*"
  to = "/customer/index.html"
  status = 200
